---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

homebrew_installed_packages:
  - aws-iam-authenticator
  - awscli
  - bash
  - bash-completion
  - bash-git-prompt
  - bat
  - fzf
  - gawk
  - gdrive
  - git
  - git-extras
  - git-hooks
  - git-lfs
  - git-standup
  - github/gh/gh
  - gnu-sed
  - gnu-tar
  - go
  - go-jsonnet
  - gpg
  - htop
  - httpie
  - hub
  - ipcalc
  - iperf
  - jq
  - kind
  - kubernetes-cli
  - kubectx
  - nmap
  - openssl
  - parallel
  - pigz
  - powerlevel10k
  - pv
  - pwgen
  - pyenv
  - pyenv-virtualenv
  - qmk/qmk/qmk
  - readline
  - shellcheck
  - sqlite
  - ssh-copy-id
  - stern
  - the_silver_searcher
  - tmux
  - tree
  - vim
  - watch
  - wagoodman/dive/dive
  - wget
  - wrk
  - yq
  - zsh-kubectl-prompt

homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - devhubapp/devhub
  - romkatv/powerlevel10k
  - superbrothers/zsh-kubectl-prompt

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - autodesk-fusion360
  - bartender
  - devhub
  - discord
  - docker
  - dropbox
  - firefox
  - font-cascadia-mono
  - font-cascadia-mono-pl
  - font-fira-code
  - font-meslo-for-powerline
  - font-meslo-lg-nerd-font
  - font-meslo-lg
  - google-backup-and-sync
#  - google-chrome
  - google-cloud-sdk
  - google-drive-file-stream
  - ibm-cloud-cli
  - istat-menus
  - iterm2
  - karabiner-elements
  - logitech-options
#  - lastpass
  - okta-advanced-server-access
  - prusaslicer
#  - slack
  - sonos
  - spotify
  - synology-surveillance-station-client
  - ultimaker-cura
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
#  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 406056744,  name: "Evernote" }
  - { id: 442160987,  name: "Flycut" }
  - { id: 926036361,  name: "LastPass" }
  - { id: 441258766,  name: "Magnet" }
  - { id: 419330170,  name: "Moom" }
  - { id: 1116599239, name: "NordVPN IKE" }
  - { id: 1142753258, name: "Ring" }
  - { id: 425955336,  name: "Skitch" }
  - { id: 747648890,  name: "Telegram" }
  - { id: 497799835,  name: "Xcode" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: gimme-aws-creds
    state: latest

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


