---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: true
configure_dock: true

homebrew_installed_packages:
  - zsh
  - git
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh-you-should-use
  - zsh-git-prompt
  #- dockutil
  # - aws-iam-authenticator
  # - awscli
  # - fzf
  # - gawk
  # - git
  # - git-extras
  # - git-hooks
  # - git-lfs
  # - git-standup
  # - github/gh/gh
  # - gnu-sed
  # - gnu-tar
  # - gpg
  # - htop
  # - httpie
  # - hub
  # - ipcalc
  # - iperf
  # - jq
  # - kind
  # - nmap
  # - openssl
  # - pigz
  # - pv
  # - pwgen
  # - pyenv
  # - pyenv-virtualenv
  # - qmk/qmk/qmk
  # - readline
  # - shellcheck
  # - sqlite
  # - ssh-copy-id
  # - stern
  # - the_silver_searcher
  # - tmux
  # - tree
  # - watch
  # - wget
  # - wrk
  # - yq

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - barrier
  #- cyberduck
  - deepl
  #- docker
  #- emacs-mac-spacemacs-icon
  - figma
  - firefox
  - font-source-code-pro
  - gas-mask
  - hammerspoon
  - github
  - google-chrome
  - hpedrorodrigues/tools/dockutil
  - insomnia
  - iterm2
  - lastpass
  - marked
  #- multipass
  - notion
  - postman
  - ql-ansilove
  - qladdict
  - qlcolorcode
  - qlcommonmark
  - qlimagesize
  - qlmarkdown
  - qlmobi
  - qlprettypatch
  - qlstephen
  - qlvideo
  - qlcolorcode
  - quicklook-csv
  - quicklook-json
  - quicklook-pfm
  - slack
  - spotify
  - telegram
  #- tidal
  #- timely
  - timeular
  - vmware-fusion
  - visual-studio-code
  - webpquicklook
  #- windscribe
  # - logitech-options
  # - synology-surveillance-station-client

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_apps:

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: gimme-aws-creds
    state: latest

dotfiles_repo: https://github.com/einSelbst/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/
dotfiles_files:
  - .zshrc
  - .zshenv
  - .zshaliases
  - .gitignore
  - .inputrc
  - .osx

dockitems_remove:
  - Maps
  - TV
dockitems_persist:
  - name: "GitHub Desktop"
    path: "/Applications/GitHub Desktop.app/"
    pos: 5

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


